### ISSUE TITLE
Cambio lista canciones aleatoria

### ISSUE THREAD

**Issue by JCarvajalr** [JCarvajalr/Bounsic#4]
It is better to structure the function in such a way that the songs start playing one after the other, as opposed to the previous code that had a menu to navigate between the songs in the same list.
Only a "for" of 7 repetitions was used to save 7 songs in a list and be played in the same loop.
 
![image](https://user-images.githubusercontent.com/129871390/234576478-da1a698e-8dd2-4449-9025-93328ac7fc53.png)

**Comment by Dxckrr** [comment]
Good job ! :D
